// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgsh5GiKYu-7zWyxisvQO8PSNwUN_AYuE',
    appId: '1:825431850356:web:511891062adf18111d4021',
    messagingSenderId: '825431850356',
    projectId: 'guvercin-b5d67',
    authDomain: 'guvercin-b5d67.firebaseapp.com',
    storageBucket: 'guvercin-b5d67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKkaGsmOqvcnq-EKmbLJYnSIVZxS6fQ2g',
    appId: '1:825431850356:android:21a6607405ba1ab91d4021',
    messagingSenderId: '825431850356',
    projectId: 'guvercin-b5d67',
    storageBucket: 'guvercin-b5d67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn4XVgYuoyRUhTOJU1KGQ6T3qnpY-8dwU',
    appId: '1:825431850356:ios:1d7568a135e0dc9b1d4021',
    messagingSenderId: '825431850356',
    projectId: 'guvercin-b5d67',
    storageBucket: 'guvercin-b5d67.firebasestorage.app',
    iosBundleId: 'com.example.guvercin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn4XVgYuoyRUhTOJU1KGQ6T3qnpY-8dwU',
    appId: '1:825431850356:ios:1d7568a135e0dc9b1d4021',
    messagingSenderId: '825431850356',
    projectId: 'guvercin-b5d67',
    storageBucket: 'guvercin-b5d67.firebasestorage.app',
    iosBundleId: 'com.example.guvercin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgsh5GiKYu-7zWyxisvQO8PSNwUN_AYuE',
    appId: '1:825431850356:web:7397b82a6e4d165f1d4021',
    messagingSenderId: '825431850356',
    projectId: 'guvercin-b5d67',
    authDomain: 'guvercin-b5d67.firebaseapp.com',
    storageBucket: 'guvercin-b5d67.firebasestorage.app',
  );

}