// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgsh5GiKYu-****************-*********',
    appId: '1:*************:web:********************',
    messagingSenderId: '*****************',
    projectId: 'guvercin-*****',
    authDomain: 'guvercin-*****.firebaseapp.com',
    storageBucket: 'guvercin-*****.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIza************-***********',
    appId: '1:825431***********:android:21a660740**************',
    messagingSenderId: '8254***********',
    projectId: 'guvercin-*****',
    storageBucket: 'guvercin-*****.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIza************-***********',
    appId: '1:825431***********:android:21a660740**************',
    messagingSenderId: '8254***********',
    projectId: 'guvercin-*****',
    storageBucket: 'guvercin-*****.firebasestorage.app',
    iosBundleId: 'com.example.guvercin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIza************-***********',
    appId: '1:825431***********:android:21a660740**************',
    messagingSenderId: '8254***********',
    projectId: 'guvercin-*****',
    storageBucket: 'guvercin-*****.firebasestorage.app',
    iosBundleId: 'com.example.guvercin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIza************-***********',
    appId: '1:825431***********:android:21a660740**************',
    messagingSenderId: '8254***********',
    projectId: 'guvercin-*****',
    authDomain: 'guvercin-*****.firebaseapp.com',
    storageBucket: 'guvercin-****.firebasestorage.app',
  );

}
